### PR TITLE
Project completed - The Next Web Clone Responsive Project

### PR DESCRIPTION
**Pull request by xtrmdarc**
We completed the next web clone project and request a code review. This is the summary of our project: 

- Add the main layout structure
- Add semantic tags
- Create CSS
- Create responsive breakpoint (Media queries used)
- Run and pass the validators

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
Just a few more changes, and project will be perfect:
* [x] In tablet version of navbar TWN logo should be present at the leftmost part ([link to page](https://thenextweb.com/))

image
* [ ] Large version of top 3 articles section should contain TWN logo at the top left corner of the row ([link to page](https://thenextweb.com/))

image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
### You did all changes required previously. :1st_place_medal: 
Before you merge to master, TNW logo should only be visible for large version of project, so please make this small correction and merge to master. 

_Goodluck in your next project_ *Happy coding*

**Pull request merged**
